api_addr: ":8000"
database_url: "host=localhost port=5432 user=postgres dbname=fsp_accounts password=admin sslmode=disable"
database_docker_url: "host=db port=5432 user=admin dbname=fsp_accounts password=admin sslmode=disable"
    