// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete user by token data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user by token data",
                "responses": {}
            }
        },
        "/account/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user data by token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user data by token",
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user token data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user token data",
                "parameters": [
                    {
                        "description": "User dto for modify user",
                        "name": "ModifyUserDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ModifyUserDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/login": {
            "post": {
                "description": "login in api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Login for user",
                "parameters": [
                    {
                        "description": "User  dto for login in",
                        "name": "userDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UserDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/account/register": {
            "post": {
                "description": "Register in api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Register for user",
                "parameters": [
                    {
                        "description": "Create user dto for register in",
                        "name": "createUserDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/companies": {
            "get": {
                "description": "Get companies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get companies",
                "responses": {}
            }
        },
        "/company": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Create company",
                "parameters": [
                    {
                        "description": "Create company dto",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateCompanyDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/company/order/{order_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get company order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Orders"
                ],
                "summary": "Get company order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "order id",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/review/{review_id}": {
            "get": {
                "description": "Get company review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Company"
                ],
                "summary": "Get company review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "review id",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete company review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Company"
                ],
                "summary": "Delete company review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/service/{service_id}": {
            "get": {
                "description": "Get service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Service"
                ],
                "summary": "Get service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service id",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/service/{service_id}/review": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create service review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Service"
                ],
                "summary": "Create service review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service id",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create service review",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateReviewServiceDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}": {
            "get": {
                "description": "Get company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Delete company",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/member": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Post company member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Post company member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create participant dto",
                        "name": "participant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateParticipantDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/member/{username}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete company member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Delete company member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/members": {
            "get": {
                "description": "Get company members",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company members",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/moderator": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Post company moderator",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Post company moderator",
                "parameters": [
                    {
                        "description": "Create participant dto",
                        "name": "participant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateParticipantDto"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/moderator/{username}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete company moderators",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Delete company moderators",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/moderators": {
            "get": {
                "description": "Get company moderators",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company moderators",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/orders": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get company orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Orders"
                ],
                "summary": "Get company orders",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/review": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create company review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Company"
                ],
                "summary": "Create company review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create company review",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateReviewCompanyDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/reviews": {
            "get": {
                "description": "Get company reviews",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Company"
                ],
                "summary": "Get company reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/service": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Service"
                ],
                "summary": "Create service",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create service dto",
                        "name": "serviceDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateServiceDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/service/{service_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Service"
                ],
                "summary": "Delete services",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service id",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/company/{company_id}/services": {
            "get": {
                "description": "Get services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company",
                    "Service"
                ],
                "summary": "Get services",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "company id",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Post order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Post order",
                "parameters": [
                    {
                        "description": "Create order dto",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateOrderDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/order/{order_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "order id",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get orders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get orders",
                "responses": {}
            }
        },
        "/service/review/{review_id}": {
            "get": {
                "description": "Get service review",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Service"
                ],
                "summary": "Get service review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "review id",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete service reviews",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Service"
                ],
                "summary": "Delete service reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "review id",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service/{service_id}/reviews": {
            "get": {
                "description": "Get service reviews",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review",
                    "Service"
                ],
                "summary": "Get service reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service id",
                        "name": "service_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/servicetype": {
            "get": {
                "description": "Get service types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceType"
                ],
                "summary": "Get service types",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create service type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceType"
                ],
                "summary": "Create service type",
                "parameters": [
                    {
                        "description": "Create service type",
                        "name": "servicetype",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateServiceTypeDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/servicetype/{id}": {
            "get": {
                "description": "Get service type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceType"
                ],
                "summary": "Get service type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete service type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceType"
                ],
                "summary": "Delete service type",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "service type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tag": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Create Tag",
                "parameters": [
                    {
                        "description": "Create tag",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateTagDto"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/tag/{id}": {
            "get": {
                "description": "Get tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Get Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Delete Tag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tag id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tags": {
            "get": {
                "description": "Get tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Get Tag",
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Get users data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get users data",
                "responses": {}
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Get user data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dtos.CreateCompanyDto": {
            "type": "object",
            "required": [
                "email",
                "inn",
                "name",
                "phone"
            ],
            "properties": {
                "avatar": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "manager_telegram": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "phone": {
                    "type": "string"
                },
                "tagsIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dtos.CreateOrderDto": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                },
                "will_be_finished_at": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateParticipantDto": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateReviewCompanyDto": {
            "type": "object",
            "required": [
                "rating"
            ],
            "properties": {
                "header": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateReviewServiceDto": {
            "type": "object",
            "required": [
                "rating"
            ],
            "properties": {
                "header": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateServiceDto": {
            "type": "object",
            "required": [
                "price",
                "service_type_id",
                "text"
            ],
            "properties": {
                "price": {
                    "type": "number"
                },
                "service_type_id": {
                    "type": "integer"
                },
                "tagsIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dtos.CreateServiceTypeDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "dtos.CreateTagDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "dtos.CreateUserDto": {
            "type": "object",
            "required": [
                "first_name",
                "password",
                "role",
                "second_name",
                "username"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 50
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "role": {
                    "description": "\"user\"/\"admin\"",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ]
                },
                "second_name": {
                    "type": "string",
                    "maxLength": 50
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "dtos.ModifyUserDto": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "balance": {
                    "type": "number"
                },
                "first_name": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dtos.UserDto": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Account API",
	Description:      "API for managing users",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
